import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import logo from '../public/logo.png'
import hero from '../public/hand-in-hand.jpg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
        <Head>
          <title>PACE&lsquo;SPORT</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={ `${styles.main} tw-overflow-x-hidden` } >
          <Navbar />
          <div>
            <header className='tw-flex tw-justify-center tw-h-36 tw-relative'>
              <div className='tw-flex tw-flex-col tw-justify-center'>
                <Image src={logo} height={70} width={70} alt="Logo Pace'sport" 
                      className='tw-rounded-full shadow-sm tw-bg-white tw-p-2'/>
              </div>
              <Image className='tw-w-full tw-h-full tw-absolute tw-object-cover -tw-z-10 tw-blur-sm tw-scale-110' src={hero} placeholder='blur' alt="Hero image"/>
            </header>
          </div>
        </main>

    </>
  )
}
